AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Daily Gratitude Notes – SAM stack (API Gateway, Lambda, DynamoDB, EventBridge, Step Functions, SES).

Parameters:
  LinkedInUrl:
    Type: String
    Default: "https://linkedin.com/in/yourprofile"
    Description: Your LinkedIn profile URL
  GitHubUrl:
    Type: String
    Default: "https://github.com/yourusername"
    Description: Your GitHub profile URL
  SenderEmail:
    Type: String
    Default: "your-email@example.com"
    Description: SES-verified sender email address (must be verified in AWS SES before deployment)
  ArchiveTimeZone:
    Type: String
    Default: "UTC"
    Description: IANA timezone for nightly deletion (e.g. "Europe/London", "Asia/Jerusalem"). Scheduler uses this to run at 23:00 local time.

Globals:
  Function:
    Runtime: python3.13
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        NOTES_TABLE: !Ref GratitudeNotesTable
        GRATITUDE_NOTES_TABLE: !Ref GratitudeNotesTable
        SENDER_EMAIL: !Ref SenderEmail
        REGION: !Ref AWS::Region
        TOKEN_SECRET: !Sub ${AWS::StackName}-secret-key
        EVENT_BUS_NAME: default
        ARCHIVE_TIMEZONE: !Ref ArchiveTimeZone

Resources:
  GratitudeNotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: gratitude_notes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: gsi_date
          KeySchema:
            - AttributeName: date
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: gsi_email_date
          KeySchema:
            - AttributeName: email
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl

  GratitudeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: DailyGratitudeApi
      StageName: prod
      EndpointConfiguration: REGIONAL
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'*'"

  StepPrepareEventFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GratitudePrepareEventFunction
      Description: Step Function task that normalizes EventBridge payloads for the gratitude note workflow.
      Handler: handlers.events.step_prepare_event.handler
      CodeUri: ../lambdas
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GratitudeNotesTable

  StepArchiveNotesFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Step Function task that archives (marks deleted) notes each night.
      Handler: handlers.events.step_archive_notes.handler
      CodeUri: ../lambdas
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GratitudeNotesTable

  PostGratitudeNotesFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Create a new daily gratitude note.
      Handler: handlers.api.post_gratitude_note.handler
      CodeUri: ../lambdas
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GratitudeNotesTable
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: "*"
      Events:
        PostGratitudeNote:
          Type: Api
          Properties:
            RestApiId: !Ref GratitudeApi
            Path: /gratitude-notes
            Method: post

  GetTodayGratitudeNotesFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: List today's gratitude notes for the public feed.
      Handler: handlers.api.get_today_gratitude_notes.handler
      CodeUri: ../lambdas
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GratitudeNotesTable
      Events:
        GetTodayNotes:
          Type: Api
          Properties:
            RestApiId: !Ref GratitudeApi
            Path: /gratitude-notes/today
            Method: get

  GetGratitudeNoteFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Get a specific gratitude note by ID.
      Handler: handlers.api.get_gratitude_note.handler
      CodeUri: ../lambdas
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GratitudeNotesTable
      Events:
        GetGratitudeNote:
          Type: Api
          Properties:
            RestApiId: !Ref GratitudeApi
            Path: /gratitude-notes/{id}
            Method: get

  DeleteGratitudeNoteFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: Delete a gratitude note by owner token.
      Handler: handlers.api.delete_gratitude_note.handler
      CodeUri: ../lambdas
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GratitudeNotesTable
      Events:
        DeleteGratitudeNote:
          Type: Api
          Properties:
            RestApiId: !Ref GratitudeApi
            Path: /gratitude-notes/{id}
            Method: delete

  PostFeedbackFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostFeedbackFunction
      Description: Receive UI/UX feedback and email it to the developer.
      Handler: handlers.api.email_feedback.handler
      CodeUri: ../lambdas
      Environment:
        Variables:
          SENDER_EMAIL: !Ref SenderEmail
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
              Resource: "*"
              Condition:
                StringEquals:
                  ses:FromAddress: !Ref SenderEmail
      Events:
        PostFeedback:
          Type: Api
          Properties:
            RestApiId: !Ref GratitudeApi
            Path: /feedback
            Method: post

  GratitudeWorkflowLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/vendedlogs/states/${AWS::StackName}-gratitude-workflow
      RetentionInDays: 30

  GratitudeWorkflowLogsPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-gratitude-workflow-logs
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowStepFunctionsToWriteLogs",
              "Effect": "Allow",
              "Principal": {
                "Service": "states.amazonaws.com"
              },
              "Action": [
                "logs:CreateLogDelivery",
                "logs:GetLogDelivery",
                "logs:UpdateLogDelivery",
                "logs:DeleteLogDelivery",
                "logs:ListLogDeliveries",
                "logs:DescribeLogGroups",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/vendedlogs/states/${AWS::StackName}-gratitude-workflow:*"
            }
          ]
        }

  GratitudeWorkflow:
    Type: AWS::Serverless::StateMachine
    DependsOn:
      - GratitudeWorkflowLogGroup
      - GratitudeWorkflowLogsPolicy
    Properties:
      Name: !Sub ${AWS::StackName}-gratitude-workflow
      Definition:
        Comment: Handle nightly archive workflow for gratitude notes.
        StartAt: PrepareEvent
        States:
          PrepareEvent:
            Type: Task
            Resource: ${PrepareFnArn}
            Next: RouteEvent
          RouteEvent:
            Type: Choice
            Choices:
              - Variable: $.eventType
                StringEquals: "archive.nightly"
                Next: ArchiveNotes
            Default: UnknownEvent
          ArchiveNotes:
            Type: Task
            Resource: ${ArchiveFnArn}
            ResultPath: "$"
            End: true
          UnknownEvent:
            Type: Fail
            Error: GratitudeUnknownEvent
            Cause: Event type not supported.
      DefinitionSubstitutions:
        PrepareFnArn: !GetAtt StepPrepareEventFn.Arn
        ArchiveFnArn: !GetAtt StepArchiveNotesFn.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref StepPrepareEventFn
        - LambdaInvokePolicy:
            FunctionName: !Ref StepArchiveNotesFn
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:DescribeLogGroups
                - logs:DescribeResourcePolicies
                - logs:PutResourcePolicy
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogStreams
              Resource: "*"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt GratitudeWorkflowLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
      Tracing:
        Enabled: true

  GratitudeWorkflowInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartWorkflowExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt GratitudeWorkflow.Arn

  GratitudeWorkflowSchedulerInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartWorkflowExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !GetAtt GratitudeWorkflow.Arn

  # NOTE:
  # We intentionally do NOT manage AWS::Scheduler::Schedule via CloudFormation because
  # this account/region has CloudFormation EarlyValidation hooks enabled that reject it during changeset creation.
  # We create the timezone-aware schedule imperatively (AWS CLI) after deployment.
  GratitudeArchiveRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${AWS::StackName}-gratitude-archive
      Description: Legacy UTC schedule (kept disabled). Real schedule is created via EventBridge Scheduler at 23:00 local time.
      ScheduleExpression: cron(0 23 * * ? *)
      State: DISABLED
      Targets:
        - Arn: !GetAtt GratitudeWorkflow.Arn
          Id: GratitudeArchiveTarget
          RoleArn: !GetAtt GratitudeWorkflowInvokeRole.Arn
          Input: '{"eventType":"archive.nightly"}'

  GratitudeWorkflowFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-gratitude-workflow-failures
      AlarmDescription: Alarm when gratitude workflow executions fail.
      Namespace: AWS/States
      MetricName: ExecutionsFailed
      Dimensions:
        - Name: StateMachineArn
          Value: !GetAtt GratitudeWorkflow.Arn
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching

  # TODO: Add CloudWatch Dashboard for monitoring
  # CloudWatch Dashboard has strict validation rules - each metric array item can only have 2 elements max
  # Need to restructure dashboard widgets to comply with CloudWatch validation
  # DailyGratitudeDashboard:
  #   Type: AWS::CloudWatch::Dashboard
  #   Properties:
  #     DashboardName: !Sub ${AWS::StackName}-DailyGratitudeDashboard
  #     DashboardBody: !Sub |
  #       { ... }

Outputs:
  GratitudeWorkflowArn:
    Description: Step Functions state machine ARN for Mission 3 workflow.
    Value: !GetAtt GratitudeWorkflow.Arn
  GratitudeWorkflowFailureAlarmName:
    Description: CloudWatch alarm monitoring gratitude workflow failures.
    Value: !Ref GratitudeWorkflowFailureAlarm
  GratitudeApiBaseUrl:
    Description: Base URL for the Daily Gratitude API (public, no API key required).
    Value: !Sub https://${GratitudeApi}.execute-api.${AWS::Region}.amazonaws.com/prod
  GratitudeNotesTableName:
    Description: Name of the gratitude_notes DynamoDB table.
    Value: !Ref GratitudeNotesTable
  # TODO: Uncomment when DailyGratitudeDashboard is added
  # DashboardURL:
  #   Description: CloudWatch Dashboard URL for Daily Gratitude metrics.
  #   Value: !Sub https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${DailyGratitudeDashboard}
